### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by andy-** [HNeukermans/ng2-signalr#92] opened 2017-11-08 21:46 UTC
Hello, i have migrated mi app from Angular 4 to Angular 5. I am getting this error: 

Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.OpaqueToken is not a constructor
    at eval (signalr.module.js:3)
    at Object.../../../../ng2-signalr/src/services/signalr.module.js (vendor.bundle.js:1566)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (signalr.js:5)
    at Object.../../../../ng2-signalr/src/services/signalr.js (vendor.bundle.js:1558)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (ng2-signalr.js:17)
    at Object.../../../../ng2-signalr/src/ng2-signalr.js (vendor.bundle.js:1494)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///../../../../ng2-signalr/index.js:1)
    at Object.../../../../ng2-signalr/index.js (vendor.bundle.js:1478)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (ops-notification.service.ts:7)
    at Object.../../../../../src/app/shared/services/ops-notification.service.ts (main.bundle.js:1502)

**Comment by mcgri** [comment] 2017-11-09 09:50
I think it's a duplicate of #86

**Comment by mcgri** [comment] 2017-11-09 10:08
@andy-  as a temporary solution, you could try to run - "npm install pbriones/ng2-signalr"

**Comment by andy-** [comment] 2017-11-10 14:26
@mcgri it worked! thanks!

**Comment by stevencohn** [comment] 2017-11-10 15:02
Any advice on how to reference pbriones' version from package.json? npm install didn't like just the string shown above by mcgri so I tried adding this line to my package.json:

		"ng2-signalr": "git+https://github.com/pbriones/ng2-signalr.git",

which worked but cloned the source files. This caused the compiler to complain that index.ts wasn't included; I then tried to add it to the tsconfig files[] but that didn't seem to help.

So what's the best way to add this so a team can consume it easily?  Thanks!

**Comment by andy-** [comment] 2017-11-10 15:43
this worked on my team: "ng2-signalr": "github:pbriones/ng2-signalr"
we use --aot flag to build and serve.

**Comment by Floyd1256** [comment] 2017-11-28 16:15
Hey guys after trying to install from the newer version of the library (pbriones' updated version), I am always getting a warning concerning angular/router. The thing is, if I check the version of angular/router, it says 3.10.10 which should be okay, but still the error persists. I am only getting the following warning:
`npm WARN ng2-signalr@2.1.1 requires a peer of @angular/router@>=3.0.0 || >= 5.0.0 but none was installed.`
However when I run the app, it is complaining about not finding index.js within the ng2-signalr folder. 
Any ideas on how to proceed?

**Comment by itsikhar** [comment] 2017-12-03 15:58
Hey @Floyd1256 
did you solved it? I have the same issue with my app..

**Comment by sreekumarp** [comment] 2017-12-03 16:23
@itsikhar : for @andy- 's solution worked.... its temporary fix .... but I found a benfit here that,... all my team members will start using --aot with there development itself 🥇 

https://github.com/HNeukermans/ng2-signalr/issues/92#issuecomment-343507355

**Comment by itsikhar** [comment] 2017-12-03 16:37
Hey @sreekumarp,
I can't use @andy- solution cause i'm working with Ionic and it doesn't support this flag.

**Comment by Floyd1256** [comment] 2017-12-04 06:39
Hey @itsikhar I actually had to transpile the downloaded module along with jquery and signalr libraries. If you get an error concerning jquery after that try to re-import it because that's what worked for me. Took me some time so I recommend waiting for the author's update if you're not in a hurry.

**Comment by itsikhar** [comment] 2017-12-04 08:30
Hey @Floyd1256 ,
Thanks for your answer, 
For now I also decided to change my service to work with jQuery untill the author will update.
Thank you :)

**Comment by andy-** [comment] 2017-12-04 19:45
@itsikhar Ionic its by default aot compiled, but you can try npm run build --prod --aot

**Comment by stevencohn** [comment] 2017-12-08 15:04
As mentioned in issue #86, this git repo has been updated to deal with OpaqueToken however it doesn't appear that this change has been published to npm yet. You can download this repo and build locally and install from the local dist folder. Or @HNeukermans could update npm! Please!?

**Comment by CBXZero** [comment] 2018-01-04 17:08
Any update on getting this to npm? Ran into the same issue and would like to use the library

**Comment by gabguy** [comment] 2018-01-08 18:41
Guys, please push this update to npm. We need it

**Comment by sreekumarp** [comment] 2018-01-17 10:44
@HNeukermans : can you please publish it ?

**Comment by zoharyosef** [comment] 2018-01-17 16:25
Joining to the request

Thanks

**Comment by sreekumarp** [comment] 2018-01-18 10:07
temporary solution is to install it from github

`npm install github:HNeukermans/ng2-signalr`


it worked for me

**Comment by OnlyAGhost** [comment] 2018-01-22 19:40
Trying to use either repository (trying to upgrade from Angular4 to Angular5) I'm getting this error:

Error: <path>\node_modules\ng2-signalr\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

Thanks!

**Comment by srivathsah** [comment] 2018-01-22 22:58
+1

**Comment by dharapvj** [comment] 2018-01-23 07:28
I forked and compiled and published this library as a temporary measure under different scope.. so that it becomes usable for Angular 5..

please use it as `npm i @dharapvj/ngx-signalr`. It will install v3.0.0 and you will not face the issue of OpaqueToken anymore.

**Comment by Groverize** [comment] 2018-01-23 09:00
I personally gave up on this project and just learnt to implement it myself with the base JQuery approach... It's fairly easy to do yourself.

**Comment by zoharyosef** [comment] 2018-01-23 09:30
@Groverize I also tried going jq, but i had funny issues with change detection...

**Comment by dharapvj** [comment] 2018-01-23 11:17
Try my package once

**Comment by zoharyosef** [comment] 2018-01-23 11:26
@dharapvj 
I tried it it's excellent
Thanks!

**Comment by dharapvj** [comment] 2018-01-23 11:43
Ha!

Thanks..

I did not do anything..

I just cloned,
did some quick edits to remove 'ng2' references
and published it under my name.

Good to know that is working for others as well.

*Cheers,*
*VJ*

**Comment by OnlyAGhost** [comment] 2018-01-23 16:34
@dharapvj works like a dream!!! Thank you so much for doing this!

**Comment by abhijeet-gandhi** [comment] 2018-01-26 14:19
@dharapvj brao! Saved my day :)

**Comment by thduttonuk** [comment] 2018-02-20 15:21
Angular 5 support has been published

**Closed by thduttonuk** 2018-02-20 15:21 UTC
