### ISSUE TITLE
This will become an error in Angular v5.x

### ISSUE THREAD

**Issue by QJesus** [HNeukermans/ng2-signalr#72] opened 2017-06-28 07:38 UTC
PS D:\HealthCare.WebNg> ng build --prod --aot
 12% building modules 17/17 modules 0 activeWarning: Can't resolve all parameters for SignalR in D:/sframed/HealthCare.WebNg/node_modules/ng
2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for SignalR in D:/sframed/HealthCare.WebNg/node_modules/ng2-signalr/src/services/signalr.d.ts: ([objec
t Object], [object Object], ?). This will become an error in Angular v5.x

**Comment by ogrim** [comment] 2017-06-30 06:12
Duplicate of #46

**Comment by HNeukermans** [comment] 2017-09-29 19:03
should be fixed in 2.1.1

**Closed by HNeukermans** 2017-09-29 19:03 UTC

**Comment by m12876d** [comment] 2017-12-04 14:29
just happened, angular 4.4
steps to reproduce
1. create a service taking anything in ctor
...
@Injectable()
export class AService
{
    constructor (private a: string)
    {   
    }

2. configure app.module to provide the service via factory

providers:
[
   { provide: AService, useFactory: AppModule.aFactory }
]
...

static aFactory(): AService
{
    return new AService('hello');
}
